#!/usr/bin/env bash

RETURN=0

dir="src include"
CPPCHECK_suppresses="--suppress=unusedFunction --suppress=missingIncludeSystem --inline-suppr"
CPPCHECK_OPTS="-Iinclude -Isrc --enable=all --error-exitcode=1 --force  $CPPCHECK_suppresses"

NORMAL="\e[m"
RED="\e[0;32;31m"
LIGHT_RED="\e[1;31m"
GREEN="\e[0;32;32m"
YELLOW="\e[1;33m"

CLANG_FORMAT=$(which clang-format)
if [ $? -ne 0 ]; then
    echo -e "${RED}[WARNING]${NORMAL}: ${YELLOW}clang-format${NORMAL} not installed." >&2
    exit 1
fi

ASPELL=$(which aspell)
if [ $? -ne 0 ]; then
    echo -e "${RED}[WARNING]${NORMAL}: ${YELLOW}aspell${NORMAL} not installed." >&2
    exit 1
fi

CPPCHECK=$(which cppcheck)
if [ $? -ne 0 ]; then
    echo -e "${RED}[WARNING]${NORMAL}: ${YELLOW}cppcheck${NORMAL} not installed." >&2
    exit 1
fi

$CPPCHECK $dir $CPPCHECK_OPTS > /dev/null
if [ $? -ne 0 ]; 
then
    RETURN=1
    echo 
    echo -e "[${RED}WARNING${NORMAL}]: Fail to pass ${YELLOW}cppcheck${NORMAL} analysis." >&2
    echo
else
    echo -e "[${GREEN}PASS${NORMAL}]: ${YELLOW}cppcheck${NORMAL} analysis."      
fi

clang-format src/* include/* -i

exit $RETURN

